#!/bin/python3

import sys
import os
import yaml

from pathlib import Path
import shutil


PKG_MANAGERS = {
    "pacman": (True, [
        ("community.general.pacman", ("package", "{0}")),
        ("when", "ansible_pkg_mgr == 'pacman'"),
        ("become", "true"),
    ], "pacman"),
    "aur": (True, [
        ("kewlfft.aur.aur", [("use", "paru"), ("name", "{0}")]),
        ("when", "ansible_pkg_mgr == 'pacman'")
    ], "paru"),
    "pkgbuild": (True, [
        ("kewlfft.aur.aur", [("use", "makepkg"), ("name", "{0}"),
            ("local_pkgbuild", "{{{{ install_src }}}}/PKGBUILDS/{0[0]}")]),
        ("when", "ansible_pkg_mgr == 'pacman'")
    ], "makepkg"),
}
STANDALONE_TASKS = os.path.abspath(os.path.join("ansible", "standalone_tasks"))


## Packages

def generate_install_file_contents(pkgs_desc):
    contents = []
    require_package_facts = False
    if "_" in pkgs_desc:
        # Alternative way allowing to comment groups
        groups = pkgs_desc["_"]
        for group in groups:
            for pkg_manager in group.keys():
                if not pkg_manager in PKG_MANAGERS.keys():
                    continue
                require_package_facts |= generate_pkgs_contents(pkg_manager, group[pkg_manager], contents)
    else:
        for pkg_manager in PKG_MANAGERS.keys():
            if not pkg_manager in pkgs_desc:
                continue
            require_package_facts |= generate_pkgs_contents(pkg_manager, pkgs_desc[pkg_manager], contents)
    if require_package_facts:
        contents.insert(0, { "include_tasks": f"{STANDALONE_TASKS}/gather_package_facts.yml" })
    return contents


def generate_pkgs_contents(pkg_manager, pkgs, contents):
    require_package_facts = False
    if not isinstance(pkgs, list):
        pkgs = [pkgs]
    str_pkgs, dict_pkgs = [], []
    for pkg in pkgs:
        if isinstance(pkg, dict):
            dict_pkgs.append(pkg)
        elif isinstance(pkg, str):
            str_pkgs.append(pkg)

    support_list, items, rename = PKG_MANAGERS[pkg_manager]
    if support_list:
        entry = { "name": f"Install {','.join(str_pkgs)} with {rename}" }
        for append in items:
            write_to_entry(entry, str_pkgs, append)
        contents.append(entry)
    else:
        for pkg in str_pkgs:
            entry = { "name": f"Install {pkg} with {rename}" }
            for append in items:
                write_to_entry(entry, pkg, append)
            contents.append(entry)

    for dict_pkg in dict_pkgs:
        name = dict_pkg["name"]
        unless = dict_pkg.get("unless")

        entry = { "name": f"Install {name} with {rename}" }
        for append in items:
            write_to_entry(entry, name, append)
        if unless is not None:
            require_package_facts = True
            if not isinstance(unless, list):
                unless = [unless]
            when = [f"'{pkg}' not in ansible_facts.packages" for pkg in unless]
            entry["when"] = " and ".join(when)
        contents.append(entry)
    return require_package_facts


def write_to_entry(entry, pkg, append):
    key, val = append
    if isinstance(val, tuple):
        sub = {}
        write_to_entry(sub, pkg, val)
        entry[key] = sub
    elif isinstance(val, list):
        sub = {}
        for subval in val:
            write_to_entry(sub, pkg, subval)
        entry[key] = sub
    else:
        if isinstance(pkg, list) and val == "{0}":
            entry[key] = pkg
        else:
            entry[key] = val.format(pkg)


## Generate

def write_yml_file(path, yml_dict):
    with open(path, "w") as file:
        dump = "\n".join([
            "# This file was auto-generated.",
            "# See `ansible/scripts/generate_playbook",
            "",
            yaml.dump(yml_dict)
        ])
        file.write(dump)


def visit_then_write_tasks(src_path, dest_path, group: str, role: str):
    tasks_dir = os.path.join(src_path, "tasks")
    if os.path.isdir(tasks_dir):
        import_tasks = [os.path.abspath(path) for path in Path(tasks_dir).rglob("*.yml")]
    else:
        import_tasks = []

    pkgs_path = os.path.join(src_path, "packages.yml")
    if os.path.isfile(pkgs_path):
        install_file_path = os.path.join(dest_path, "install_packages.yml")
        with open(pkgs_path, "r") as fs:
            try:
                pkgs_desc = yaml.safe_load(fs)
                install_contents = generate_install_file_contents(pkgs_desc)
                if install_contents:
                    write_yml_file(install_file_path, install_contents)
                    import_tasks.insert(0, "install_packages.yml")
            except yaml.YAMLError:
                print(f"YAML file '{pkgs_path}' cannot be parsed.", file=sys.stderr)

    main = [{"import_tasks": task} for task in import_tasks]
    write_yml_file(os.path.join(dest_path, "main.yml"), main)

    print(f"Written tasks for {group}/{role}")


if __name__ == "__main__":
    generated_dir = os.path.join(".generated", "roles")
    roles = []

    for group in os.listdir("roles"):
        roles_dir = os.path.join("roles", group)
        if not os.path.isdir(roles_dir):
            continue

        for role in os.listdir(roles_dir):
            role_dir = os.path.join(roles_dir, role)
            if not os.path.isdir(role_dir):
                continue
            mapped_role_dir = os.path.join(generated_dir, role)

            tasks_dir = os.path.join(mapped_role_dir, "tasks")
            for dir in [tasks_dir]:
                if not os.path.isdir(dir):
                    os.makedirs(dir)

            visit_then_write_tasks(role_dir, tasks_dir, group, role)
            handlers_dir = os.path.join(role_dir, "handlers")
            if os.path.isdir(handlers_dir):
                shutil.copytree(handlers_dir, os.path.join(mapped_role_dir, "handlers"))
            meta_dir = os.path.join(role_dir, "meta")
            if os.path.isdir(meta_dir):
                shutil.copytree(meta_dir, os.path.join(mapped_role_dir, "meta"))
            roles.append({"role": role, "tags": [group, role]})

    playbook = [{
        "name": "Setup dotfiles",
        "hosts": "local",
        "vars_files": [
            "../ansible/vars/dirs.yml",
            "../ansible/vars/misc.yml",
            "env_vars.yml",
        ],
        "roles": roles,
    }]
    write_yml_file(os.path.join(".generated", "playbook.yml"), playbook)
