#!/bin/sh

# FIXME: make it work without AUR dependency
GRADLE_HOME=$HOME/gradle /usr/bin/jdtls \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xmx2G \
  -data "${1:-$HOME/workspace}" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED

