- name: Create GNUPG config directory
  file:
    path: "{{ install_dest }}/.gnupg"
    state: directory
- name: Link GNUPG agent config
  file:
    src: "{{ install_src }}/roles/base/gnupg/files/gpg-agent.conf"
    dest: "{{ install_dest }}/.gnupg/gpg-agent.conf"
    state: link
