_:
  # Dynamic menus
  - pacman: [dmenu, rofi, rofi-calc]
    aur: [rofi-greenclip]

  # General tools
  - pacman: [flameshot, libnotify, dunst, sxiv, feh]
  - pacman:
    - name: picom
      unless: picom-git

  # Audio
  - pacman: [libpulse, pipewire-pulse, pavucontrol, pamixer]

  # Network
  - pacman: [networkmanager, network-manager-applet]
    aur: [networkmanager-dmenu-git]

  # Used Fonts
  - pacman: [fontforge, ttf-jetbrains-mono, ttf-jetbrains-mono-nerd, ttf-iosevka-nerd]

  # Fallback Fonts
  - pacman: [noto-fonts, noto-fonts-emoji, noto-fonts-extra]

  # Themes
  - pacman: lxappearance

  # GUI File Management
  - pacman: [thunar, tumbler, ffmpegthumbnailer, engrampa]

  # Polkit
  - pacman: [polkit, lxsession]
