#!/bin/sh
xset r rate 600 35
xset b 0 0 0
xset b off

[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"
[[ -f "$HOME/.xbindkeysrc.scm" ]] && xbindkeys -f "$HOME/.xbindkeysrc.scm"
[[ -f "$HOME/.Xresources" ]] && xrdb -load "$HOME/.Xresources"

[[ -f "$HOME/.xinitrc-local" ]] && source "$HOME/.xinitrc-local"
[[ -f "$HOME/.inputremap" ]] && sh "$HOME/.inputremap"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Set wallpaper
[[ -f "$HOME/.local/state/qde/wallpaper.x11" ]] && sh "$HOME/.local/state/qde/wallpaper.x11"

# Fixes
export _JAVA_AWT_WM_NONREPARENTING=1
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# Reset pipes
function mkpipe {
    if [[ -p "$1" ]]; then
        rm "$1"
    fi
    mkfifo "$1"
}

source "$HOME/.xinitwm"
