#!/bin/dash
if [ -z "$QDE_WORKSPACES" ]; then
    exit 1
fi

jq_bin="jq"
if ! command -v &> /dev/null; then
    # jaq is 4x faster in this case!
    jq_bin="jaq"
fi
focused_ws=$(hyprctl monitors -j | "$jq_bin" -cr '.[] | select(.focused) | .activeWorkspace.name')
win_count_map=$(hyprctl workspaces -j | "$jq_bin" -c 'map({key: .name, value: .windows}) | from_entries')
if [ "$jq_bin" = "jaq" ]; then
    # jaq doesn't support unique_by
    unique_entries_workaround="to_entries | map({key: .value, value: .value}) | from_entries"
    echo "$QDE_WORKSPACES" | jaq -nR -c --color never \
        --arg win_count_map "$win_count_map" \
        --arg focused_ws "$focused_ws" \
        '[inputs, $focused_ws] | '"$unique_entries_workaround"' | to_entries | map({name: .value, windows: (($win_count_map | fromjson)[.value]//0), focused: (.value == $focused_ws)})'
else
    echo "$QDE_WORKSPACES" | jq -nR -Mc \
        --argjson win_count_map "$win_count_map" \
        --arg focused_ws "$focused_ws" \
        '[inputs, $focused_ws] | to_entries | unique_by(.value) | sort_by(.key) | map({name: .value, windows: ($win_count_map[.value]//0), focused: (.value == $focused_ws)})'
fi

