#!/bin/sh
export EDITOR=nvim

export XDG_CONFIG_HOME="$HOME/.config"

# PATH
PATH="$HOME/.luarocks/bin:$PATH"
PATH="$HOME/.pub-cache/bin:$PATH"
PATH="$HOME/.yarn/bin:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"

PATH="$HOME/.local/bin:$PATH"

# Fixes
export GPG_TTY=$(tty)
export _JAVA_AWT_WM_NONREPARENTING=1
