#!/bin/sh
# vim:fdm=marker

## ZSH config {{{
# zsh:history/search
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_ALL_DUPS

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# zsh:dir
setopt autocd

# zsh:keybindings
bindkey -v
bindkey "^k" up-line-or-beginning-search
bindkey "^j" down-line-or-beginning-search
bindkey '^[[Z' reverse-menu-complete

# zsh:completion
autoload -Uz compinit; compinit
setopt MENU_COMPLETE
zstyle ":completion:*" menu select

# zsh:prompt
autoload -Uz promptinit; promptinit
if [[ "$TERM" != "dumb" ]]; then
    setopt PROMPT_SUBST
    autoload -Uz vcs_info
    zstyle ":vcs_info:*" enable git
    zstyle ":vcs_info:git*" formats "  %b"
    precmd() { vcs_info; }

    # reminder: these need to stay single quotes to expand later, not on read
    PS1='%F{red}%(?.. <%?>)%F{magenta}${vcs_info_msg_0_} %F{black}%f '
    RPS1="%F{blue}%~%f"
else
    PS1="%(?..[%?] )%n@%m:%~ " # based on default prompt 'walters'
fi
## }}}

## Sourcing {{{
# zsh:syntax-highlighting
_ZSH_SHL_SOURCE="/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
if [[ -f $_ZSH_SHL_SOURCE ]]; then
    source "$_ZSH_SHL_SOURCE"
fi

# source z.lua
if [[ -f /usr/share/z.lua/z.lua ]]; then
    eval "$(/usr/share/z.lua/z.lua --init zsh)"
fi

_TMUX_EXT_SOURCE="$HOME/.config/tmux/tmux_ext.sh"
if [[ -f $_TMUX_EXT_SOURCE ]]; then
    time source "$_TMUX_EXT_SOURCE"
else
    alias ta="tmux attach -t"
fi
## }}}

## Aliases {{{
alias ssh="TERM=xterm-256color ssh"

# history aliases
alias hist="vim ~/.zsh_history"
alias inhist="history 0 | grep -i"

# require confirmation on main file ops
alias cp="cp --interactive"
alias mv="mv --interactive"
alias rm="rm --interactive"

# automatic colors
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# common operations
alias cl="clear"
alias la="ls -a"
alias lh="ls -lh"
alias ll="ls -lah"
alias yank="xclip -selection clipboard"

# git
alias g="git"
alias ga="gita"
alias gs="git status"
alias lg="lazygit"

# alias vim and vi to nvim if installed
if type nvim > /dev/null; then
    alias vim="nvim"
    alias vi="nvim"
fi
alias f="xplr"
alias j="just"
alias c="cargo"
alias fl="flutter"

alias nf="neofetch"
alias nfr="neofetch --config none"

alias ts="tree-sitter"
alias octperm="stat -c %a"
## }}}

## Misc tools {{{
function rsed { find . -type f -exec sed -i "s|$1|$2|g" {} +; }
function rsedg { find . -type f -exec sed -i "s/$1/$2/g" {} +; }

function synctime {
    sudo sh -c 'ntpd -gq && hwclock --systohc'
}
## }}}
