#!/bin/sh

function install {
    ln -s "$(pwd)/$1" "$HOME/${2:-$1}" 2>/dev/null
}

function install_all {
    ln -s "$(pwd)/$1"/* "$HOME/${2:-$1}/" 2>/dev/null
}

install .xmonad
install .config/alacritty
install .config/wezterm
install .zshrc
install .zshenv
install .Xresources
install .Xmodmap
install .ideavimrc
install .vimrc
install .xinitrc
install .gitconfig

install_all .config
install_all .local/bin

echo "Done"

# TODO: qdf.toml once QDF becomes usable
