- name: Create lazygit config directory
  file:
    path: "{{ install_dest }}/.config/lazygit"
    state: directory
- name: Link lazygit config
  file:
    src: "{{ install_src }}/roles/workflow/misctools/files/lazygit.yml"
    dest: "{{ install_dest }}/.config/lazygit/config.yml"
    state: link
- name: Link neofetch config
  file:
    src: "{{ install_src }}/roles/workflow/misctools/files/neofetch.conf"
    dest: "{{ install_dest }}/.config/neofetch/config.conf"
    state: link
