- name: Create neofetch config directory
  file:
    path: "{{ install_dest }}/.config/neofetch"
    state: directory
- name: Link neofetch config
  file:
    src: "{{ install_src }}/roles/workflow/misctools/files/neofetch.conf"
    dest: "{{ install_dest }}/.config/neofetch/config.conf"
    state: link
