- name: Link unread-bell config
  file:
    src: "{{ install_src }}/roles/apps/discord/unread-bell"
    dest: "{{ install_dest }}/.config/unread-bell"
    state: link
- name: Install unread-bell pacman hook
  template:
    src: "{{ install_src }}/roles/apps/discord/templates/patch-unread-bell.hook.j2"
    dest: "/etc/pacman.d/hooks/patch-unread-bell.hook"
  become: true
