- name: Link .zshrc
  file:
    src: "{{ install_src }}/roles/workflow/zsh/files/zshrc"
    dest: "{{ install_dest }}/.zshrc"
    state: link
- name: Remove .zshenv
  file:
    path: "{{ install_dest }}/.zshenv"
    state: absent
- name: Link .zprofile
  file:
    src: "{{ install_src }}/roles/workflow/zsh/files/zprofile"
    dest: "{{ install_dest }}/.zprofile"
    state: link
