- name: Link .zshrc
  file:
    src: "{{ install_src }}/roles/workflow/zsh/files/zshrc"
    dest: "{{ install_dest }}/.zshrc"
    state: link
- name: Create .zshenv
  template:
    src: "{{ install_src }}/roles/workflow/zsh/templates/zshenv.j2"
    dest: "{{ install_dest }}/.zshenv"
  vars:
    PATH:
    - $HOME/.local/bin
    - $HOME/.cargo/bin
    - $HOME/.cabal/bin
    - $HOME/.ghcup/bin
    - $HOME/.yarn/bin
    - $HOME/.luarocks/bin
    - $GOPATH/bin
