#!/bin/sh

# Prepare named pipes
mkpipe "/tmp/xmonad-info"
mkpipe "/tmp/discord.pipe"

# Variables used in xmonad config
export XMONAD=$HOME/.xmonad
export XMONAD_CONFIG_DIR=$XMONAD/bin/xmonad
export XMONAD_DATA_DIR=$XMONAD_CONFIG_DIR
[[ ! -d $HOME/.cache/xmonad ]] && mkdir -p $HOME/.cache/xmonad
export XMONAD_CACHE_DIR=$XDG_CACHE_HOME/xmonad

export XMOBAR_CONFIG_DIR=$XMONAD/bin/xmobar

# Start xmonad
exec qmonad
