#!/bin/sh
OVERLAY_FILE=${WALLPAPER_OVERLAY_FILE:-"$HOME/Pictures/wallpaper-overlay.png"}

SAVEFILE_DIR="$HOME/.local/state/qde"
SAVEFILE_PREFIX="$SAVEFILE_DIR/wallpaper"
SAVEFILE_HEADER="#!/bin/sh\n# Auto Generated - $0\n"

wallpaper=$(sxiv -brot ~/Wallpapers | head -n1)
if [ -z "$wallpaper" ]; then
    exit 0
fi
set_to="$wallpaper"
extra_info=""
if [[ -f $OVERLAY_FILE ]]; then
    kdialog --title "Set Wallpaper" --yesno "Overlay file found.\nApply it?"
    if [[ $? -eq 0 ]]; then
        set_to="$HOME/.active-wallpaper.png"
        extra_info=" (overlay applied)"
        convert "$wallpaper" $OVERLAY_FILE \
            -background None -gravity Center -resize 2560x -extent 2560x1440 \
            -composite -compose Over \
            "$set_to"
    fi
fi
mkdir -p "$SAVEFILE_DIR"
if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    savefile="${SAVEFILE_PREFIX}.wayland"
    echo -e "${SAVEFILE_HEADER}pkill swaybg\nswaybg --image '$wallpaper' --mode fill" > "$savefile"
else
    savefile="${SAVEFILE_PREFIX}.x11"
    echo -e "${SAVEFILE_HEADER}feh --no-fehbg --bg-fill '$wallpaper'" > "$savefile"
fi
chmod +x "$savefile"
"$savefile"
notify-send "Wallpaper Set" "${wallpaper##*/}$extra_info"
