" vim:ft=vim
"
" Minimal .vimrc with no plugins
" to use as an alternative when nvim config cannot be used.
" Also used as a base in .ideavimrc.

" General settings
set nocompatible encoding=utf8
set noerrorbells
set lazyredraw

set number relativenumber 
set hidden
set wrap linebreak
set noshowmatch
set magic
set wildmenu
set tabstop=4 softtabstop=4 shiftwidth=4
set smarttab expandtab

set ignorecase smartcase
set incsearch hlsearch

" Theme
filetype plugin indent on
syntax on

set termguicolors t_Co=256
if exists('+termguicolors')
    " fix to make colors feel right within tmux
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

colorscheme slate

set cursorline
hi! link Preproc Constant
hi! link CursorLineNr Constant
hi! link CursorLine TabLineSel

hi clear IncSearch
hi IncSearch guifg=gray50 gui=bold
hi! link Search IncSearch

match Error /\t/

" Keybindings
nnoremap <SPACE> <Nop>
let mapleader=" "

nnoremap <leader>w :w<CR>
nnoremap <leader>fs :w<CR>
nnoremap <leader>, :e#<CR>

nnoremap <leader>d "_d
nnoremap <leader>D "_D
nnoremap <CR> :nohl<CR>

" indendation related bindings
nnoremap <leader>k kcc
nnoremap <leader>j jcc
nnoremap <leader>o o<ESC>cc
nnoremap <leader>O O<ESC>cc

inoremap <C-K> <C-P>
inoremap <C-J> <C-N>

" window/tab/file/buffer movements
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set nosplitbelow splitright

nnoremap <leader>sp :tabp<CR>
nnoremap <leader>sn :tabn<CR>

nnoremap [q :cp<CR>
nnoremap ]q :cn<CR>
nnoremap Q :ccl<CR>
