- name: Create hypr config directory
  file:
    path: "{{ install_dest }}/.config/hypr"
    state: directory
- name: Link Hyprland main config file
  file:
    src: "{{ install_src }}/roles/desktop/hyprland/files/hyprland.conf"
    dest: "{{ install_dest }}/.config/hypr/hyprland.conf"
    state: link
- name: Link Hyprland config partials directory
  file:
    src: "{{ install_src }}/roles/desktop/hyprland/files/hyprland"
    dest: "{{ install_dest }}/.config/hypr/hyprland"
    state: link
