- name: Create tmux config directory
  file:
    path: "{{ install_dest }}/.config/tmux"
    state: directory
- name: Link tmux.conf
  file:
    src: "{{ install_src }}/roles/workflow/tmux/files/tmux.conf"
    dest: "{{ install_dest }}/.config/tmux/tmux.conf"
    state: link
- name: Link plugins.tmux
  file:
    src: "{{ install_src }}/roles/workflow/tmux/files/plugins.tmux"
    dest: "{{ install_dest }}/.config/tmux/plugins.tmux"
    state: link
- name: Link tmux-attach bin
  file:
    src: "{{ install_src }}/roles/workflow/tmux/bins/tmux-attach"
    dest: "{{ install_dest }}/.local/bin/tmux-attach"
    state: link
