- name: Link .Xresources
  file:
    src: "{{ install_src }}/roles/desktop/qde/files/Xresources"
    dest: "{{ install_dest }}/.Xresources"
    state: link

- name: Create dunst config directory
  file:
    path: "{{ install_dest }}/.config/dunst"
    state: directory
- name: Link dunstrc
  file:
    src: "{{ install_src }}/roles/desktop/qde/files/dunstrc"
    dest: "{{ install_dest }}/.config/dunst/dunstrc"
    state: link

- name: Create picom config directory
  file:
    path: "{{ install_dest }}/.config/picom"
    state: directory
- name: Link picom.conf
  file:
    src: "{{ install_src }}/roles/desktop/qde/files/picom.conf"
    dest: "{{ install_dest }}/.config/picom/picom.conf"
    state: link

- name: Link greenclip.toml
  file:
    src: "{{ install_src }}/roles/desktop/qde/files/greenclip.toml"
    dest: "{{ install_dest }}/.config/greenclip.toml"
    state: link

- name: Create QDE data directory
  file:
    path: "{{ install_dest }}/.local/share/qde"
    state: directory
- name: Check if src quickview dir exists
  stat:
    path: "{{ install_src }}/priv/quickview"
  register: qde_main_qvcheck
- name: Link quickview directory
  file:
    src: "{{ install_src }}/priv/quickview"
    dest: "{{ install_dest }}/.local/share/qde/quickview"
    state: link
  when: qde_main_qvcheck.stat.isdir is defined and qde_main_qvcheck.stat.isdir
