[greenclip]
use_primary_selection_as_input = true
enable_image_support = true
blacklisted_applications = []

max_selection_size_bytes = 0
trim_space_from_selection = true
history_file = "$HOME/.cache/clipboard-history"
image_cache_directory = "/tmp/greenclip"

max_history_length = 50
static_history = []
