#!/bin/dash
wm=$(qdectl getwm)
if [ "$wm" = "hyprland" ]; then
    qdectl getworkspaces
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        qdectl getworkspaces
    done
elif [ "$wm" = "xmonad" ]; then
    qwmhctl getworkspaces --listen
else
    exit 1
fi
