- name: Setup dotfiles locally
  hosts: local

  vars_files:
    - env_vars.yml

  pre_tasks:
  - name: Ensure elevation privileges are granted
    command: "whoami"
    changed_when: False
    become: yes
  - name: Ensure dotfiles destination directory exists
    file:
      path: "{{ install_dest }}"
      state: directory
      mode: "0755"
  - name: Ensure XDG config directory exists
    file:
      path: "{{ install_dest }}/.config"
      state: directory
      mode: "0755"

  - name: Install PARU helper
    kewlfft.aur.aur:
      name: paru
      use: makepkg
      state: present
    when: ansible_pkg_mgr == 'pacman'

  roles:
    - role: git
      tags: [base, git]
    - role: vim
      tags: [minimal, vim]
    - role: zsh
      tags: [workflow, shell]
    - role: tmux
      tags: [workflow, tmux]
    - role: gittools
      tags: [workflow, gittools]

    - role: x11
      tags: [desktop, x11]
    - role: qde
      tags: [desktop, qde]
    # - role: xmonad
    #   tags: [desktop, xmonad]
    - role: kitty
      tags: [desktop, workflow, terminal, kitty]

    - role: rust
      tags: [lang, rust]

    - role: udev-rules
      tags: [desktop, system, udev-rules]
