#!/bin/dash
QDE_LIB=${QDE_LIB:-$(dirname $(readlink -f "$0"))}

wm=$("$QDE_LIB/getwm")
if [ $? -ne 0 ]; then
    exit 1
fi

# $1: workspace name
# $2: workspace id
if [ "$wm" = "xmonad" ]; then
    xdotool key "super+$2"
elif [ "$wm" = "hyprland" ]; then
    hyprctl dispatch workspace "name:$1"
else
    exit 1
fi
