- name: Prepare local machine for dotfiles binary usage
  hosts: local

  vars_files:
  - ../ansible/vars/dirs.yml

  pre_tasks:
  - name: Ensure python3-pip is installed (pacman)
    community.general.pacman:
      package:
      - python-pip
    when: ansible_pkg_mgr == 'pacman'
    become: true

  tasks:
  - name: Install pick module (pip)
    pip:
      name: pick
