- name: Setup dotfiles locally
  hosts: local

  vars_files:
    - ../ansible/vars/dirs.yml
    - ../ansible/vars/misc.yml
    - ../ansible/env_vars.yml

  roles:
    - role: git
      tags: [base, git]
    - role: vim
      tags: [base, vim]
    - role: ssh
      tags: [base, ssh]
    - role: gnupg
      tags: [base, gnupg]

    - role: misctools
      tags: [workflow, misctools]
    - role: zsh
      tags: [workflow, shell]
    - role: tmux
      tags: [workflow, tmux]
    - role: nvim
      tags: [workflow, nvim]

    - role: x11
      tags: [desktop, x11]
    - role: qde
      tags: [desktop, qde]
    - role: xmonad
      tags: [desktop, xmonad]
    - role: kitty
      tags: [desktop, workflow, terminal, kitty]
    - role: alacritty
      tags: [desktop, terminal, alacritty]
    - role: wezterm
      tags: [desktop, terminal, wezterm]

    - role: udev-rules
      tags: [desktop, system, udev-rules]
    - role: greetd
      tags: [desktop, system, greetd]

    - role: rust
      tags: [lang, rust]

    - role: intellij
      tags: [apps, intellij]
